### PR TITLE
Unit handler: added unit_context_block, renamed 'bad'

### PR DESCRIPTION
**Pull request by Putnam3145**
Been given permission to talk about headers and structures and things, so I'm just going to add stuff as I need it (turns out Lua scripting is real helpful for debugging without needing to recompile, whoop)

### CODE REVIEW

**Comment by lethosor** [comment]
Thanks! I am a bit cautious of renaming long-lived fields like this from our end. It seems like the only place we use `units.bad` is in `scripts/devel/find-offsets.lua`, so that is not too hard to update.

**Comment by Putnam3145** [comment]
There's a bit of a move to name things more correctly to help communication with the Toady One, or so I've heard, so I went ahead with that. And yeah, I figured nothing was using it much, since it is, in fact, full of bad pointers

**Comment by lethosor** [comment]
Maybe we could make `original-name` a valid attribute for fields as well?

**Review by lethosor — APPROVED** [review]

**Comment by lethosor** [comment]
scripts fix: https://github.com/DFHack/scripts/pull/507

**Pull request merged**
