### PR TITLE
added missing field in viewscreen_optionst

### PR DESCRIPTION
**Pull request by pronvit**

### CODE REVIEW

**Comment by lethosor** [comment]
Ah, was this part of the padding between `in_abandon_dwf` and `sel_idx`? That would explain why DFHack-created instances of this screen were randomly ending the game.

**Comment by pronvit** [comment]
Yeah, it's initialised to 0 on OS X always (at least for me) but was ending game on other platforms, took time to understand what the hell.

**Comment by lethosor** [comment]
I was having issues with it about 10% of the time on OS X (with [this script](https://github.com/lethosor/dfhack-scripts/blob/master/mute.lua)). You can set the `MallocScribble` environment variable on OS X to fill uninitialized memory with 0xAA, by the way.

**Comment by pronvit** [comment]
Thx. I just keep forgetting about padding and that missing fields can be right there, otherwise it's clear from the render() method, which address it checks.

Btw, in your script, you don't need to show the options screen itself, just instantiate it, use it to show the volume screen and `delete` it. I believe you can also delete the volume screen manually, to prevent flickering.

**Pull request merged**
