### PR TITLE
change `tiletype_shape::RAMP_TOP` `walkable` attr to false

### PR DESCRIPTION
**Pull request by ab9rf**
based on research by @plule 

necessary to implement suspendmanager @plule also found evidence that other tools are working around this being wrong

see dfhack/dfhack#3492

### CODE REVIEW

**Comment by plule** [comment]
Thanks!

**Comment by myk002** [comment]
I'm not entirely sure this is the correct solution. ramp tops *are* walkable from a pathability perspective, which is what I think is the sense intended here. However, you're right in that every current usage really wants to know if the tile is "standable".

Current sample usages:

create-unit:
```lua
  elseif locationType == 'Walkable' then
    if tileShapeAttrs.walkable and tileShapeAttrs.basic_shape ~= df.tiletype_shape_basic.Open then
      return true
    end
    return false
  end
```

deep-embark:
```lua
  local shapeAttrs = df.tiletype_shape.attrs[tiletypeAttrs.shape]
  if shapeAttrs.walkable and shapeAttrs.basic_shape ~= df.tiletype_shape_basic.Open then -- downward ramps are walkable but open; units placed here would fall
    return true
  else
    return false
  end
```

build-now:
```lua
    -- reject unwalkable or open tiles
    if not shape_attrs.walkable then return false, false end
    if shape_attrs.basic_shape == df.tiletype_shape_basic.Open then
        return false, false
    end
```

so is it better to change the semantics of the current `walkable` attribute or should we add an almost-identical `standable` attribute?

**Comment by ab9rf** [comment]
i will point out that these attributes are solely for DFHack use and can mean whatever we want them to mean. i am not sure that it's worth maintaining a "walkability" attribute separate from "standability" that _nothing uses_

also, ramp tops are only conditionally walkable, and the unit never actually stands _on_ the ramp top. i'm not sure it serves any useful purpose to characterize them as walkable

**Comment by myk002** [comment]
That's fair. I'm good with this change then

**Review by myk002 — APPROVED** [review]
I like the branch name

**Comment by myk002** [comment]
tacked on a similar change for ENDLESS_PIT

**Pull request merged**
