### PR TITLE
Identified artifact claims. Factored out/renamed type

### PR DESCRIPTION
**Pull request by PatrikLundell**

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Doesn't make much sense to have the were race in a vector, but it matches up with all were types in a ported 0.44.12 save and a 0.47.01 save. The were caste is still AWOL, however. Possibly it might go into the second vector only when there's more than 1? If so, someone arena savvy would have to test that. In the 0.47.01 save the 3 last vectors contained data for some transformations of an unknown type (i.e. there wasn't anything in the data identifying it with a name or anything else I could use, and those had a 0 length race vector).

**Comment by PatrikLundell** [comment]
Syndrome caste was indeed in the next vector, but apparently only if there was a choice. By hacking the syndrome I managed a were to transform into a female Demon Rat instead. Changing the caste tag to Male did nothing, but adding a 1 in a new element to the caste vector worked.
The caste did not reflect into the unit's curse wound, but the changed race did change the "curse_caste" field. Thus, the curse_race field was moved and the curse_caste field dropped.
Fixes #364

**Comment by BenLubar** [comment]
looks like my changes yesterday conflicted with these

@PatrikLundell can you merge or rebase with the master branch? (rebase preferred)

**Comment by PatrikLundell** [comment]
Odd, given that I pulled the master branch before I started, forcing me to resolve one conflict.
I think I've managed to resolve it, although I have no idea how the integer->enum change was removed in the first place.

**Pull request merged**
