### PR TITLE
Aligned performance_skills

### PR DESCRIPTION
**Pull request by PatrikLundell**
Addresses the first point of issue #346 (I'm not addressing the issue with hash here, as that seems to cause auto resolution, and this is only one part of it).

### CODE REVIEW

**Comment by lethosor** [comment]
Only certain keywords cause auto-resolution, by the way: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by BenLubar** [comment]
The keywords that cause auto-resolution get a dotted underline that links to that article (or somewhere else, I don't quite remember)

**Comment by lethosor** [comment]
@PatrikLundell just to verify, what OS and DF architecture are you testing with? (It would be helpful to know where you've tested this in case these turn out to be pointers or longs or something weird instead of int32s, although I think int32_t is a safe guess here.)

**Comment by PatrikLundell** [comment]
Ah, a good question, of course. I'm on Windows 64 bits.

I use int32_t as the default when I don't have any idea about what it is, as that shouldn't blow up anything, and can be split or merged as required later. int32_t can be viewed with gui/gm-editor to get some idea, and I tried that, but didn't get anything but 0 for them (among a bunch of just embarked dorfs in a new world, so the sample size is small). I did verify that the performance skills of a number of the dorfs matched the number of skills in each category, by the way.

**Comment by lethosor** [comment]
Ah, in that case, there's a decent chance it's a pointer, which would break on 32-bit builds (not that 32-bit support is particularly important). I might be able to verify on a 32-bit build later, though.

**Comment by PatrikLundell** [comment]
Ah, you mean a 32 bit system would assign only 32 bits rather than 64 bits, causing two 32 bit ints to push the rest out of alignment? That would go the other way as well though, where a 32 bit system examiner would assign a single 32 bit int when it is in fact a pointer, pushing the 64 bit data out of alignment.
I can't see there's any other way around that than comparing everything on both a 32 bit and a 64 bit system to find those pesky pointers, in particular if they're null (that has the advantage of actually making it possible to find pointers that rarely are assigned, though, unless they're buried in a sea of zeroes, which isn't unusual).

**Comment by lethosor** [comment]
Right, testing on both is the only way to be sure (well, disassembling can work in some cases too)

**Comment by cvuchener** [comment]
Tested on linux64, and it looks good. I reported this because the value is not a pointer, so we can be sure of that. A pair of int32_t makes it a pair of "1" so it makes sense to me.

I could not test linux32 for other reasons. Bug reports are coming soon.

**Pull request merged**
