### PR TITLE
Item vmethod_107 is assignQuality2

### PR DESCRIPTION
**Pull request by Bumber64**
Method is called at end of `assignQuality`. Update return types to `item_quality`.

### CODE REVIEW

**Comment by ab9rf** [comment]
the description provided looks accurate for the generic implementation, but `item_ammost`'s implementation is rather more complicated

**Review by ab9rf — APPROVED** [review]

**Comment by Bumber64** [comment]
> the description provided looks accurate for the generic implementation, but `item_ammost`'s implementation is rather more complicated

I was looking at `item_instrumentst`'s, which seems to call the same function. I skimmed through some functions where it was checking if the unit was living and had emotions, various other flags, etc.

**Comment by ab9rf** [comment]
the generic one is used by:
* item_actualst
* item_ballistaarrowheadst
* item_barst
* item_blocksst
* item_body_componentst
* item_boulderst
* item_branchst
* item_cheesest
* item_corpsepiecest
* item_corpsest
* item_critterst
* item_drinkst
* item_eggst
* item_fish_rawst
* item_fishst
* item_globst
* item_liquid_miscst
* item_meatst
* item_petst
* item_plant_growthst
* item_plantst
* item_powder_miscst
* item_remainsst
* item_rockst
* item_roughst
* item_seedsst
* item_skin_tannedst
* item_smallgemst
* item_threadst
* item_verminst
* item_woodst
* itemst

the more complicated one is used by:
* item_ammost
* item_amuletst
* item_animaltrapst
* item_anvilst
* item_armorst
* item_armorstandst
* item_backpackst
* item_bagst
* item_ballistapartsst
* item_barrelst
* item_bedst
* item_binst
* item_bookst
* item_boxst
* item_braceletst
* item_bucketst
* item_cabinetst
* item_cagest
* item_catapultpartsst
* item_chainst
* item_chairst
* item_clothst
* item_coffinst
* item_coinst
* item_constructedst
* item_crownst
* item_crutchst
* item_doorst
* item_earringst
* item_figurinest
* item_flaskst
* item_floodgatest
* item_foodst
* item_gemst
* item_glovesst
* item_gobletst
* item_gratest
* item_hatch_coverst
* item_helmst
* item_instrumentst
* item_millstonest
* item_orthopedic_castst
* item_pantsst
* item_pipe_sectionst
* item_quernst
* item_quiverst
* item_ringst
* item_scepterst
* item_sheetst
* item_shieldst
* item_shoesst
* item_siegeammost
* item_slabst
* item_splintst
* item_statuest
* item_tablest
* item_toolst
* item_totemst
* item_toyst
* item_traction_benchst
* item_trapcompst
* item_trappartsst
* item_weaponrackst
* item_weaponst
* item_windowst

i am fairly, but not completely, certain that all of the types in the second group are item_constructedst and its subclasses

**Comment by myk002** [comment]
@ab9rf does this PR need any more changes?

**Review by ab9rf — APPROVED** [review]

**Pull request merged**
