### PR TITLE
Add "All" group attr to new unit_action_type enums

### PR DESCRIPTION
**Pull request by Bumber64**
Add enum attrs so all `unit_action_type` enums are in the `All` `unit_action_type_group`.

They may also need attrs for `Movement`, `MovementFeet`, `Combat`, and/or `Work` (however we decide that).

### CODE REVIEW

**Comment by ab9rf** [comment]
What's the use case for this attribute?

**Comment by myk002** [comment]
are these types handled by the action timers API in Units.cpp?

**Comment by Bumber64** [comment]
> are these types handled by the action timers API in Units.cpp?

Looks like `HoldItem`, `Mount`, and `Dismount` are?

`ReleaseItem`, `LeadAnimal`, and `StopLeadAnimal` return `nullptr` for `getActionTimerPointer`. So do `Jump`, `ReleaseTerrain`, `Parry`, and `Block`, despite already being in the `All` group.

**Comment by myk002** [comment]
ok, if there are no additional timers to handle, then this looks good to me. will merge after @quietust approves

**Comment by myk002** [comment]
seems ok -- @quietust please tell me if you have any comments

**Pull request merged**
