### PR TITLE
5005 baseline

### PR DESCRIPTION
**Pull request by ab9rf**
this is an omnibus wrapup of pending updates at the time analysis on 50.05 started

### CODE REVIEW

**Review by myk002 — APPROVED** [review]
@quietust is it alright that we merge your commit with this PR?

**Comment by myk002** [comment]
I'll see if I can prep a matching PR for DFHack/develop

**Comment by lethosor** [comment]
If we are merging the global name changes, we should also merge https://github.com/DFHack/df_misc/pull/25 at the same time. `devel/dump-offsets` is similar but can be updated separately.

**Comment by myk002** [comment]
I'll just merge this now so we're all consistent and fix develop later today

**Pull request merged**
