### PR TITLE
add unit_get_physical_description symbol

### PR DESCRIPTION
**Pull request by nornagon**
ref https://github.com/DFHack/dfhack/pull/1476

### CODE REVIEW

**Comment by BenLubar** [comment]
@nornagon can you rebase this onto the current df-structures? I think that's why the build is failing on my end.

**Comment by nornagon** [comment]
@BenLubar rebased. If you're still seeing a build issue, what's the issue?

**Comment by lethosor** [comment]
This time the osx64 build mysteriously failed (https://buildmaster.lubar.me/executions/execution-details?executionId=218563&noAutoRedirect=y)... not your fault, or anything wrong with your code, it's just a custom build server we have set up.

Also, did this PR have another address besides the osx64 one before the rebase? I thought it had two, but maybe I was thinking of something else.

**Comment by nornagon** [comment]
uh yes, whoops. that'll show me for editing things in the github ui. fixed.

**Comment by nornagon** [comment]
Yep, those are all the ones I found so far. Should I find the other
versions before merging or is doing it in a follow up ok?
-- 

j

**Comment by lethosor** [comment]
Fine to do it later, just didn't want to merge this if you were actively working on it. (If you're able to find the rest, that would be awesome, but I'm not sure how difficult that is)

**Pull request merged**
