### PR TITLE
add length to graphicst

### PR DESCRIPTION
**Pull request by myk002**
though the actual array lengths need real values

There is one vector and 24 int32_t fields added somewhere inside of what we currently call `texture_indices4`

Is there an easy way to figure out where the split is?

### CODE REVIEW

**Comment by ab9rf** [comment]
how much of this applies to 50.11 as well? do we want to backport?

**Comment by myk002** [comment]
the interface_set changes could apply to 50.11, and some of the index count changes, but the indices5 split is only 50.12

**Comment by myk002** [comment]
only the `graphic` numbers in the table above are legit. the PR was temporarily switched to target `master` in order for the size check action to run

**Comment by myk002** [comment]
merging since this is better than what we had, though we still need to look at possible size mismatches in graphicst

**Pull request merged**
