### PR TITLE
Add main_hover_instruction enum (tooltip IDs)

### PR DESCRIPTION
**Pull request by lethosor**
For dfhack/dfhack#3773
Generated by https://github.com/DFHack/scripts/pull/835, with some IDs manually added.

This is a pretty large enum... maybe there is a better way to do this.

Also open to renaming. The name is loosely inspired by DF, with the `main_` prefix added.

### CODE REVIEW

**Review by ab9rf — APPROVED** [review]
better than what we have currently so go with it

**Comment by myk002** [comment]
retargeted this PR to master since the 5010-beta branch has been merged into master and deleted

**Comment by myk002** [comment]
I see this is still marked as a draft -- is this PR able to be merged?

**Comment by myk002** [comment]
for when this get merged, the (current) main consumer of this enum will be https://github.com/DFHack/scripts/blob/master/internal/confirm/specs.lua

**Comment by myk002** [comment]
I'm good with this change -- I thought that it was still in progress, though, since it was marked as a draft. I think we can merge it (and immediately use it in `confirm`).

**Pull request merged**
