### PR TITLE
enumerate `language_word_table.words`/`.parts`

### PR DESCRIPTION
**Pull request by Shim-Panze**
Still figuring out how to mess with xml docs, so pardon any syntax blunders.
I used `TheX` `OfX` instead of `TheCompound` `OfCompound` to keep the standard with other existing enums

### CODE REVIEW

**Comment by myk002** [comment]
could you add a changelog entry?

**Comment by lethosor** [comment]
I'm torn on whether this is big enough to need a changelog entry. It really just adds descriptive names to a couple static-array indices, but the numeric indices will still work too (I think)

pre-commit does need fixing, though:

pre-commit.ci autofix

**Review by myk002 — APPROVED** [review]
Fair enough. no changelog entry needed then.

**Review by lethosor — APPROVED** [review]
I confirmed that `words[0]` and `words.FrontCompound` both give the same vector from Lua, so LGTM

**Comment by lethosor** [comment]
Squashed locally, and evidently that does not auto-close the PR, but it was merged in 978396dfa565453d02b211cd48cbe3a4a9d71ece

**Pull request closed without merging**
