### PR TITLE
De-anon-ify all structures.

### PR DESCRIPTION
**Pull request by quietust**
DFHack/dfhack#2219

Because otherwise people will use them in scripts, which is bad because removing/renaming one anon field renames ALL OTHER anon fields in the same structure.

Next step: update codegen to forbid unnamed fields so this never has to be done ever again.

### CODE REVIEW

**Comment by quietust** [comment]
Note: this change will cause the "building-hacks" plugin to break because it uses `general_ref_creaturest` objects to store custom data and references the "anon_1" and "anon_2" fields (which are now named "unk_1" and "unk_2").

Incidentally, `gui/unit-info-viewer` has been broken for over _4 and a half years_ because it referenced `unit.enemy.undead.anon_7` - it first broke during c531a09019e521fabb3c943bb49f831f635c309f and then d921898d21b8ac5d7eaa6d706635c0a19ae8eddb gave it a proper name (`undead_name`).

**Comment by myk002** [comment]
Why are you changing the names from `anon_` to `unk_` ? Wouldn't it be better to allow the scripts/plugins that are using the current names to continue to use the current names?

**Comment by myk002** [comment]
I also see usages of `anon_` in `devel/save-version.lua`, `exportlegends.lua`, and (commented) in `workorder.lua`

**Comment by quietust** [comment]
> Why are you changing the names from anon_ to unk_ ? Wouldn't it be better to allow the scripts/plugins that are using the current names to continue to use the current names?

I changed all of the `anon_X` variables to `unk_X` specifically to force all existing scripts to stop using names that could potentially change without warning _and without any possibility of tracking_ - because the "anon" names were dynamically generated, there's no references to them within df-structures itself, so if one of them changes and a script breaks then there won't be any easy way to determine what the new field name is supposed to be (because the commit history will just say that some unnamed field was renamed to "bar", rather than specifically saying that a field name "unk_5" was renamed to "bar").

I suppose I _could_ have explicitly assigned "anon_X" names to all of the unnamed fields and then changed codegen.pl at the same time to never autogenerate them again, but it's a bit late for that now.

**Comment by lethosor** [comment]
I am supportive of breaking uses of `anon_`. All of the uses that @myk002 mentioned in dfhack/scripts are dynamic references - specifically:

- devel/save-version was designed specifically to support DFHack versions _before_ the field it checks was named. Removing that support probably won't affect anyone, but if we don't remove it, the script has to continue referring to `anon_2`.
- exportlegends iterates over all fields and does nothing with fields named `anon_1` or `anon_2`. Maybe this should also include `unk` fields now.

**Comment by quietust** [comment]
> I suppose I _could_ have explicitly assigned "anon_X" names to all of the unnamed fields and then changed codegen.pl at the same time to never autogenerate them again, but it's a bit late for that now.

I just realized that making the existing `anon_X` names permanent wouldn't really have worked, because it's very possible that scripts referencing `anon_X` fields are **already broken** - we need to go through all of them anyways to make sure they're actually pointing at the right fields, and forcing them to change to various `unk_X` fields will make it possible to determine whether or not they've actually been checked.

**Review by myk002 — APPROVED** [review]
Before we merge, could you queue up PRs to fix the known uses of anon fields in the dfhack and scripts repos?

**Pull request merged**
