### PR TITLE
Added memory flag to emotions

### PR DESCRIPTION
**Pull request by PatrikLundell**
Addresses the memory flag part of issue 255, but not the additional value one (which is in a different file)

### CODE REVIEW

**Comment by PatrikLundell** [comment]
Thanks BenLubar! That's a relief. I tried to compile with Stonesense on my end (as that's vaguely where things failed), but fail to do that because there's some hard coding to look for the compiler at C: when it's installed at D: (I've modified install-debug.bat to point at the correct location, but obviously Stonesense uses some other file, somewhere). Moving back to compile without Stonesense, then.

**Comment by lethosor** [comment]
Stonesense doesn't use any separate hardcoded paths - its only build file is its own CMakeLists.txt, which doesn't have "C:" in it anywhere. Were you running a different "generate" script to build with Stonesense, maybe?

**Comment by BenLubar** [comment]
@PatrikLundell if you open the folder `%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC` (paste it into Explorer's address bar), does it go to the correct folder? (The one on D: that includes `vcvarsall.bat`)

**Comment by PatrikLundell** [comment]
Thanks for the answers. No, it can't find the C:\ folder it claims to resolve to, so I assume the symbol is incorrect. Not that surprising, given how bugged the installation of the compiler was...
I'll try to look into that.
Meanwhile, things tend to be slow, but the building has been going on for quite some time (>100 minutes). Is that expected?

**Comment by BenLubar** [comment]
The build finished successfully <https://buildmaster.local.lubar.me/executions/execution-details?executionId=69057>, but there were a bunch of garbage log messages caused by the new way of making Windows builds.

I restarted the build after I updated the BuildMaster plugin to strip out those messages, but there was also a core build waiting in the queue, and pull requests have a much lower priority than core builds.

**Comment by BenLubar** [comment]
@PatrikLundell [generate-MSVC-release.bat](https://github.com/DFHack/dfhack/blob/develop/build/win64/generate-MSVC-release.bat) includes stonesense. The `gui` version of the script opens up cmake-gui, which is probably not what you want.

**Comment by PatrikLundell** [comment]
Good point. I have no idea of whether any other flags may be involved (I haven't seen anything, but that doesn't mean much).
'relived' might not be the best alternative (and that goes for the comment as well), as there are three versions of the message part: "relived", "dwelling upon", and "remembering" (tied to the emotion_type), so using "relived" might lead the reader thought to just that text version. What about "recollected_memory"?

**Comment by PatrikLundell** [comment]
I've never understood the C/Unix crowd's pathological aversion to typing. All the single finger peckers ought to have died out long ago...

**Pull request merged**
