### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by PatrikLundell**
Resolves issue #284

### CODE REVIEW

**Comment by PatrikLundell** [comment]
"Error: Cannot convert property "UseNinja" value "" to Boolean type." indicates there's something not quite right with the new build stuff.

**Comment by lethosor** [comment]
BuildMaster isn't new at all, but @BenLubar is experimenting with switching from Make to Ninja and probably didn't configure a setting for df-structures PRs correctly (since it's a separate project).

**Comment by PatrikLundell** [comment]
I meant the change no Ninja when I said "the new build stuff"... The sooner we find out there's more work needed in that department the sooner BenLubar can take a look at it.

Anyway, I realized I'd forgotten the changelog, so I'm trying to add that now (had a frustrating trip where the script compilation failed but the VS one didn't, resulting in me eventually nuking everything and starting from scratch, derailing my thoughts. Not the first time. the script fails to refresh object files that then end up referencing stuff that doesn't exist anymore, but this time I probably removed more than I should have, when trying to "clean" manually),

**Comment by lethosor** [comment]
What's "the script"? Are you building in VS *and* something else?

If you're just building in VS, the issue with object files not updating is a known issue, and usually rebuilding a second time fixes it (without needing to clean anything). Incidentally, switching to Ninja is part of the process to fix that, also mentioned at https://github.com/DFHack/dfhack/pull/1325

**Comment by PatrikLundell** [comment]
I'm building in VS to see that it actually compiles, and I'm using install-debug.bat to see both that it actually compiles that way too and to copy the results. The weird thing is that the .bat script doesn't seem to use the same files as VS does, resulting in two different sets of files. So far I've managed to get VS to compile by using 'clean' first.

**Comment by lethosor** [comment]
Can't you just install from Visual Studio? I'd make sure you're using the same build folder (win32 vs win64) each time (across VS and whatever else you're doing); I can't think of a reason why they would be using different files. If you search for names of a specific object file, do multiple results come up?

**Comment by PatrikLundell** [comment]
I know it worked to install from VS sometime before I reinstalled it, but I haven't tried since.
In the new clone I've got one Release and one RelWithDebInfo because I forgot to change in in VS, but I had changed it in the botched version (which I wiped after making the new clone).

**Comment by BenLubar** [comment]
Whoops, I fixed the build plan but forgot to re-run the build. Running it now.

**Comment by lethosor** [comment]
Oh, so you are doing separate builds intentionally. If you want to save time, I'd go with just RelWithDebInfo, since it's nearly the same but with a few more warnings enabled.

**Comment by PatrikLundell** [comment]
RelWithDebInfo is what I try to use. Release is just a case of forgetting to change inside VS. For script changes I fall back onto VS only when the script fails, while for code I start with VS (as that's where the code is) and move to the script only when it's time to try it out.

**Comment by PatrikLundell** [comment]
After updating changelog.txt I realized it's in the main repo...
This is what I added:
```

## Structures
- Added/updated performance info:
  - ``musical_form``: Named voices field
  - ``musical_form_instruments``: named minimum_required and maximum_permitted
  - ``dance_form``: Named musical_form_id and musical_written_content_id 
  - ``written_content``: Named form_id
  - ``activity_event_performancest``: Renamed poem as written_content_id
  - ``activity_event_performancest.participant_actions``: Updated sub_type comment
  - ``incident_sub6_performance``: Made performance_event an enum
  - ``incident_sub6_performance.participants``: Named performance_event and role_index
  - ``incident_sub6_performance``: Named poetic_form_id, musical_form_id, and dance_form_id
```

**Pull request merged**
