### PR TITLE
Fixes to training_assignment fields

### PR DESCRIPTION
**Pull request by pronvit**

### CODE REVIEW

**Comment by lethosor** [comment]
Is it possible that the first two bits are a single field, like [tile_designation::dig](https://github.com/DFHack/df-structures/blob/e33762ecb50f4f3b624c08d3dd0dac9352363660/df.map.xml#L88)?

**Comment by lethosor** [comment]
Never mind, looks right to me in 0.43.03.

**Comment by pronvit** [comment]
Yeah it worries me a bit that they (and last two) are mutually exclusive, but don't know how to find out what the actual definition in Toady's code is.

**Comment by lethosor** [comment]
I noticed that setting any_trainer and any_unassigned_trainer displayed "A" and "any unassigned trainer" (from two different categories), so I'm pretty sure that part isn't an enum.

**Comment by pronvit** [comment]
Yep, good test.

**Pull request merged**
