### PR TITLE
attempt to realign with master changes

### PR DESCRIPTION
**Pull request by myk002**
based on https://github.com/DFHack/df-structures/commit/3b029079b7efd2f664c9fb5567dca68b11755c19

### CODE REVIEW

**Comment by myk002** [comment]
@quietust could you possibly check my work here?

**Comment by quietust** [comment]
I'm pretty sure the only change that should be necessary (aside from removing the compound) is growing texture_indices1 from 119 to 120 - all of the others should already be correct.

**Comment by myk002** [comment]
I re-counted the additions in 51.01 as offsets from the counts in https://github.com/DFHack/df-structures/commit/3b029079b7efd2f664c9fb5567dca68b11755c19 to get the numbers in textures 2, 3, and 4, which differ wildly from the numbers that existed. I could just restore the counts (other than the 119 -> 120 change) for now, but I do think this needs to be rechecked eventually.

**Comment by quietust** [comment]
The modifications in commit 3b029079b7efd2f664c9fb5567dca68b11755c19 were from **incorrect** values, but the values present in commit 210c145b40dbd876a29e23527c66c2a19de9c89d were already correct to begin with.

**Pull request merged**
