### PR TITLE
Unit action type groups

### PR DESCRIPTION
**Pull request by wolfboyft**
For DFHack/dfhack#2374

### CODE REVIEW

**Comment by wolfboyft** [comment]
Hmm, wait, timer_action not action_timer-- though, does it matter?

**Comment by myk002** [comment]
Yeah, I think I'd vote for `unit_action_type_timer_group`

also..changelog?

**Comment by wolfboyft** [comment]
Ack, changelog, changelog. man i hope i dont forget when doing my own stuff.

Also, I went for "timer action type" because the action types considered have timers. they are timer-type action types. i think this is the best way to have it.

**Comment by myk002** [comment]
@lethosor what would be the "expected" name here? (once we decide, both the type name and the type name named in changelog should be adjusted -- they don't currently match)

**Comment by lethosor** [comment]
I would suggest keeping `unit_action` in the name, without anything in the middle, since that's the thing you're labeling.

But taking a step back, I think this is a weird thing to name, which to me indicates that we might want to reconsider its scope. It's essentially "groups of `unit_action_type` values, but only if they correspond to actions that have `timer` fields". This is not a pattern we use in other places, as far as I know.

One alternative you could consider is to give *every* unit_action_type a group (or groups), with the group enum named `unit_action_type_group` or something similarly generic like before, then introduce a separate `has-timer` attribute for actions that have timers, and check both of those attributes from your code. That is admittedly more complicated, but avoids the special-purpose groups. Giving groups a specialized purpose could potentially confuse people who _want_ logical groupings for every `unit_action_type`, regardless of whether it has a timer, but I'm not sure if there is a realistic use-case for that.

Another option could be to rename the group enum back to something generic, give every unit_action_type one or more groups, and then have a list of only the types you care about in your code. I think your action timer API is the only place where you actually care which action types have timers, right? Could you just skip the ones that don't there?

(side note: `unit_action_type_category` or `unit_action_type_class` would be acceptable in my book as well. We use `_class` in df.job-types.xml but it could potentially be confused for OOP classes.)

**Review by myk002 — APPROVED** [review]

**Pull request merged**
