### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by PatrikLundell**
Resolves issue #260 

#261 happened while I was doing this, and it took two attempts to sync that, hence 3 commits rather than 1.

### CODE REVIEW

**Comment by lethosor** [comment]
I'd prefer `incident_performance` for the struct name and `performance` for the pointer.

**Comment by PatrikLundell** [comment]
I disagree. The reason for that is that when we're dealing with overloaded pointers I believe it should be abundantly clear which one is which so the wrong one isn't used by mistake.

**Comment by lethosor** [comment]
I was thinking turning `subtype` into an enum might help with that.

**Comment by lethosor** [comment]
Fair enough, we can deal with it later.

**Pull request merged**
