### PR TITLE
Automated df-structures update for DF 0.47.05

### PR DESCRIPTION
**Pull request by DFHack-Urist**
This is an automated pull request. Only one such pull request should be made for each Dwarf Fortress release. If this bot is malfunctioning, contact BenLubar on IRC.

### CODE REVIEW

**Review by lethosor — COMMENTED** [review]
Holding off for a bit in order to get some 0.47.04 changes released

**Comment by cvuchener** [comment]
I think there is a new int32_t (or smaller) somewhere before `unit_personality.needs`.

**Comment by cvuchener** [comment]
`unit_personality.combat_hardened` did not move, so the new field is between them (from testing with linux32/linux64).

**Comment by lethosor** [comment]
Good to know - if that's the case, we'd need to drop 0.47.04 support

**Pull request merged**
